# Generated by Django 2.2 on 2021-02-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0002_auto_20210210_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_html',
            field=models.TextField(blank=True, editable=False, verbose_name='正文 html 代码'),
        ),
    ]
